/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./../src/assets/svg/ArrowIcon.vue')['default']
    BackArrowIcon: typeof import('./../src/assets/svg/BackArrowIcon.vue')['default']
    BarcodeIcon: typeof import('./../src/assets/svg/BarcodeIcon.vue')['default']
    CheckIcon: typeof import('./../src/assets/svg/CheckIcon.vue')['default']
    CreateIcon: typeof import('./../src/assets/svg/CreateIcon.vue')['default']
    GenerateIcon: typeof import('./../src/assets/svg/GenerateIcon.vue')['default']
    GitHubIcon: typeof import('./../src/assets/svg/GitHubIcon.vue')['default']
    HeartIcon: typeof import('./../src/assets/svg/HeartIcon.vue')['default']
    InfoIcon: typeof import('./../src/assets/svg/InfoIcon.vue')['default']
    LightThemeIcon: typeof import('./../src/assets/svg/LightThemeIcon.vue')['default']
    LogoIcon: typeof import('./../src/assets/svg/LogoIcon.vue')['default']
    QrIcon: typeof import('./../src/assets/svg/QrIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareIcon: typeof import('./../src/assets/svg/ShareIcon.vue')['default']
    TelegramIcon: typeof import('./../src/assets/svg/TelegramIcon.vue')['default']
    TranslateIcon: typeof import('./../src/assets/svg/TranslateIcon.vue')['default']
    TrashIcon: typeof import('./../src/assets/svg/TrashIcon.vue')['default']
  }
}
