/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./../src/assets/svg/ArrowIcon.vue')['default']
    BackArrowIcon: typeof import('./../src/assets/svg/BackArrowIcon.vue')['default']
    BarcodeIcon: typeof import('./../src/assets/svg/BarcodeIcon.vue')['default']
    CheckIcon: typeof import('./../src/assets/svg/CheckIcon.vue')['default']
    CreateIcon: typeof import('./../src/assets/svg/CreateIcon.vue')['default']
    DarkModeIcon: typeof import('./../src/assets/svg/DarkModeIcon.vue')['default']
    DarkModIcon: typeof import('./../src/assets/svg/DarkModIcon.vue')['default']
    GenerateIcon: typeof import('./../src/assets/svg/GenerateIcon.vue')['default']
    GitHubIcon: typeof import('./../src/assets/svg/GitHubIcon.vue')['default']
    HeartIcon: typeof import('./../src/assets/svg/HeartIcon.vue')['default']
    InfoIcon: typeof import('./../src/assets/svg/InfoIcon.vue')['default']
    LightModeIcon: typeof import('./../src/assets/svg/LightModeIcon.vue')['default']
    LightThemeIcon: typeof import('./../src/assets/svg/LightThemeIcon.vue')['default']
    LogoIcon: typeof import('./../src/assets/svg/LogoIcon.vue')['default']
    QrIcon: typeof import('./../src/assets/svg/QrIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareIcon: typeof import('./../src/assets/svg/ShareIcon.vue')['default']
    TelegramIcon: typeof import('./../src/assets/svg/TelegramIcon.vue')['default']
    TheHeader: typeof import('./../src/components/header/TheHeader.vue')['default']
    ThemeToggler: typeof import('./../src/components/header/ThemeToggler.vue')['default']
    TranslateIcon: typeof import('./../src/assets/svg/TranslateIcon.vue')['default']
    TrashIcon: typeof import('./../src/assets/svg/TrashIcon.vue')['default']
    UiButton: typeof import('./../src/components/ui/UiButton.vue')['default']
    UiIcon: typeof import('./../src/components/ui/UiIcon.vue')['default']
    UiLink: typeof import('./../src/components/ui/UiLink.vue')['default']
    UiSelect: typeof import('./../src/components/ui/UiSelect.vue')['default']
    UiText: typeof import('./../src/components/ui/UiText.vue')['default']
    UiTextInput: typeof import('./../src/components/ui/UiTextInput.vue')['default']
    UiThemeToggler: typeof import('./../src/components/ui/UiThemeToggler.vue')['default']
    UiToggler: typeof import('./../src/components/ui/UiToggler.vue')['default']
  }
}
