/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const inject: typeof import('vue')['inject']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useMainStore: typeof import('../src/stores/main')['useMainStore']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useRouter: typeof import('vue-router')['useRouter']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const watch: typeof import('vue')['watch']
}
