/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const getGraphics: typeof import('../src/utils/exportFunctions')['getGraphics']
  const getSvgs: typeof import('../src/utils/exportFunctions')['getSvgs']
  const inject: typeof import('vue')['inject']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useLangStore: typeof import('../src/stores/lang')['useLangStore']
  const useMainStore: typeof import('../src/stores/main')['useMainStore']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const watch: typeof import('vue')['watch']
}
