/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const generateBarcode: typeof import('../src/composables/generateBarcode')['generateBarcode']
  const getGraphics: typeof import('../src/composables/exportFunctions')['getGraphics']
  const getQr: typeof import('../src/composables/exportFunctions')['getQr']
  const getSvgs: typeof import('../src/composables/exportFunctions')['getSvgs']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useBarcodeStore: typeof import('../src/stores/barcode')['useBarcodeStore']
  const useComposableStore: typeof import('../src/stores/composable')['useComposableStore']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useElementSize: typeof import('@vueuse/core')['useElementSize']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useNotificationStore: typeof import('../src/stores/notification')['useNotificationStore']
  const useQRCode: typeof import('@vueuse/integrations')['useQRCode']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useScroll: typeof import('@vueuse/core')['useScroll']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const watch: typeof import('vue')['watch']
}
